2021-08-06 20:35:01,070 INFO    MainThread:18012 [wandb_setup.py:_flush():69] setting env: {}
2021-08-06 20:35:01,070 INFO    MainThread:18012 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '3e3cc4dd14c6ab7234edf0ac194d05235579734b'}
2021-08-06 20:35:01,070 INFO    MainThread:18012 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '3e3cc4dd14c6ab7234edf0ac194d05235579734b'}
2021-08-06 20:35:01,071 INFO    MainThread:18012 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-06 20:35:01,071 INFO    MainThread:18012 [wandb_init.py:_log_setup():337] Logging user logs to E:\UCB\2021 Summer\GEnerative\MCR2\wandb\run-20210806_203501-1gcaju78\logs\debug.log
2021-08-06 20:35:01,071 INFO    MainThread:18012 [wandb_init.py:_log_setup():338] Logging internal logs to E:\UCB\2021 Summer\GEnerative\MCR2\wandb\run-20210806_203501-1gcaju78\logs\debug-internal.log
2021-08-06 20:35:01,072 INFO    MainThread:18012 [wandb_init.py:init():370] calling init triggers
2021-08-06 20:35:01,072 INFO    MainThread:18012 [wandb_init.py:init():375] wandb.init called with sweep_config: {}
config: {}
2021-08-06 20:35:01,072 INFO    MainThread:18012 [wandb_init.py:init():419] starting backend
2021-08-06 20:35:01,072 INFO    MainThread:18012 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-08-06 20:35:01,074 INFO    MainThread:18012 [backend.py:ensure_launched():135] starting backend process...
2021-08-06 20:35:01,079 ERROR   MainThread:18012 [wandb_init.py:init():787] error
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\wandb_init.py", line 761, in init
    run = wi.init()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\wandb_init.py", line 422, in init
    backend.ensure_launched()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\backend\backend.py", line 137, in ensure_launched
    self.wandb_process.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
